export const products = [
  {
    "name": "PRICE:",
    "price": "N/A",
    "print": "N/A",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "N/A",
    "components": "N/A",
    "details": "N/A",
    "category": "N/A",
    "lining": "N/A",
    "pockets": "N/A",
    "wash_care": "N/A",
    "styling_tip": "N/A",
    "delivery": "N/A",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RANGREZ BLAZER SET",
    "price": "10000/-",
    "print": "RANGREZ",
    "textile": "N/A",
    "fit": "slightly over sized blazer and shorts",
    "fabric": "modal satin",
    "components": "2",
    "details": "printed blazer with printed high waist shorts",
    "category": "matching moods",
    "lining": "yes",
    "pockets": "one side pocket in the shorts",
    "wash_care": "dry clean only",
    "styling_tip": "pair it with nude or gold heels or gold flats with minimal gold accessories",
    "delivery": "7 - 10 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "rangrez dhoti blazer set",
    "price": "10000/-",
    "print": "rangrez",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "modal satin",
    "components": "2",
    "details": "relaxed fit blazer with a high waist dhoti skirt",
    "category": "matching moods",
    "lining": "yes",
    "pockets": "no",
    "wash_care": "dry clean only",
    "styling_tip": "pair with gold earrings, heel or jutti\u2019s and a choker to make it indo-western",
    "delivery": "7 - 10 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAAT PRINT SHARARA CAPE SET",
    "price": "N/A",
    "print": "RAAT",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "2",
    "details": "LOOSE KAFTAN JACKET, WITH HIGH WAIST SHARARA",
    "category": "MATCHING MOODS",
    "lining": "NO",
    "pockets": "ONE",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "PAIR IT WITH JUTTI\u2019S AND A KUNDAN OR POLKI CHOKER FOR AN INDIAN LOOK OR WITH HEELS AND GOLD HOOPS TO MAKE THE LOOK WESTERN",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "block print palazzo co-ord",
    "price": "7000/- and 10000/-",
    "print": "block print",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "mul",
    "components": "2 and 3",
    "details": "elastic bandeau and palazzo pants or cropped blazer pants",
    "category": "matching moods",
    "lining": "yes",
    "pockets": "yes one in pant",
    "wash_care": "dry clean only",
    "styling_tip": "PAIR IT WITH OUR BLOCK PRINT CROPPED BLAZER OR WEAR IT AS IS WITH NUDE HEELS AND GOLD ACCESSORIES",
    "delivery": "7 to 10 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "pastel embroidered coord set",
    "price": "11000/-",
    "print": "N/A",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "mul",
    "components": "2",
    "details": "hand embroidered blouse and straight high waist pants with embroidery on the hem",
    "category": "matching moods",
    "lining": "yes",
    "pockets": "yes on one side",
    "wash_care": "dry clean only",
    "styling_tip": "Keep accessories tonal and minimal for understated luxury. Black heels. Layer with an oversized blazer for a sharp contemporary finish.",
    "delivery": "10-15 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "multi colored phulkari cape co-ord set",
    "price": "11500",
    "print": "N/A",
    "textile": "phulkari",
    "fit": "N/A",
    "fabric": "viscose muslin",
    "components": "3",
    "details": "flowy unstructured cape, cropped blouse, palazzo pants with phulkari work on the hem, cape and blouse",
    "category": "matching moods",
    "lining": "yes",
    "pockets": "yes, one",
    "wash_care": "dry clean only",
    "styling_tip": "Style with pearl accessories and white sandals for softer occasion dressing",
    "delivery": "20-25 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "Ravel Waist Coat Pant Set",
    "price": "8000",
    "print": "ravel",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "viscose muslin",
    "components": "2",
    "details": "wide collared waist coat",
    "category": "N/A",
    "lining": "N/A",
    "pockets": "N/A",
    "wash_care": "N/A",
    "styling_tip": "N/A",
    "delivery": "N/A",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL PRINT CORSET SKIRT SET",
    "price": "N/A",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "CORSET WITH BACK TIE UP ENCLOSURE, FLARED SKIRT",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES ONE SIDE OF THE SKIRT",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "ARTIFICIAL PEARL JEWELLERY, WITH COLOURFUL FOOTWEAR THAT MATCHES THE TOP",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAAT PRINT SKIRT JACKET SET",
    "price": "N/A",
    "print": "RAAT",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "2",
    "details": "STANDING HIGH COLLAR SLIGHTLY LOOSE JACKET, BUTTONS ON THE JACKET ARE ONLY FOR SHOW. AN A LINE SKIRT",
    "category": "MATCHING MOODS",
    "lining": "YES IN THE JACKET, NOT IN THE SKIRT",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "PAIR THIS SET WITH A BLACK CAMISOLE OR BANDEAU WITH GOLD ACCESSORIES AND HEELS",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAAT PRINT CAPE SKIRT SET",
    "price": "N/A",
    "print": "RAAT",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "2",
    "details": "LOOSE KAFTAN JACKET, WITH AN A LINE SKIRT",
    "category": "MATCHING MOODS",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "gold accessories and gold or black footwear",
    "delivery": "7-10 days",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL PRINT DHOTI SKIRT BLAZER SET",
    "price": "N/A",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "CROPPED BLAZER AND PLEATED DHOTI SKIRT",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "PAIR WITH OXIDIZED JEWELLERY",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "52 BAGH PHULKARI BLAZER SET",
    "price": "N/A",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FITTED",
    "fabric": "MUL",
    "components": "2",
    "details": "CROPPED BLAZER AND STRAIGHT PANTS, FRONT FIXED BELT WITH BACK ELASTIC",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "WHITE HEELS AND A DELICATE NECK PIECE",
    "delivery": "45-60 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "PASTEL EMBROIDERY WHITE BLAZER SET",
    "price": "N/A",
    "print": "N/A",
    "textile": "N/A",
    "fit": "SLIGHTLY FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "EMBROIDERY PATCH ON ON THE BLAZER, POCKET ON ONE SIDE WITH PALAZZO PANTS",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "WITH A KUNDAN SET AND WHITE HEELS",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE PRINT COORD SET",
    "price": "N/A",
    "print": "MARBLE",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "RELAXED FIT SHIRT WITH STRIAGHT PANTS (FIXED FRONT BELT WITH BACK ELASTIC)",
    "category": "MATCHING MOODS",
    "lining": "ONLY IN THE BOTTOMS",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "NUDE HEELS, AND GOLD JEWELLERY. CAN ALSO BE WORN WITH A BANDEAU OR OUR BUTTERFLY CROP TOP",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "BOHO STAR PRINT DHOTI CAPE SET",
    "price": "N/A",
    "print": "BOHO STAR",
    "textile": "N/A",
    "fit": "SLIGHTLY RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "3",
    "details": "HALTER CROP TOP, LONG KAFTAN JACKET, PLEATED DHOTI SKIRT",
    "category": "MATCHING MOODS",
    "lining": "YES IN THE DHOTI ONLY",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "PINK HEELS AND GOLD OR PINK STATEMENT EARRINGS",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "BLACK GEOMETRIC PHULKARI BLAZER SET",
    "price": "N/A",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FITTED",
    "fabric": "MUL",
    "components": "2",
    "details": "SLEEVELESS BLAZER WITH STRAIGHT PANTS, BACK ELASTIC",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "BLACK CLOSED HEELS OR FLAT SANDALS WITH BLACK EARRINGS",
    "delivery": "30 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL PRINT DHOTI CAPE SET",
    "price": "N/A",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "KAFTAN JACEKT WITH PLEATED DHOTI SKIRT",
    "category": "MATCHING MOODS",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "PAIR IT WITH A BLACK CAMISOLE, BRALETTE OR BANDEAU OR WITH OUR RAVEL PRINTED BUTTERFLY CROP TOP WITH BLACK OR GOLD FOOTWEAR",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "CROPPED BLAZER WITH SHORTS",
    "price": "8999",
    "print": "N/A",
    "textile": "BLOCK PRINT",
    "fit": "FITTED",
    "fabric": "Mul, Cotton cutwork",
    "components": "2",
    "details": "HIGH WAIST SHORTS WITH A CROPPED BLAZER",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "WITH FLAT BLACK SANDALS OR BLACK HEELS",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "CUBE PRINT SHARARA SET",
    "price": "N/A",
    "print": "CUBE",
    "textile": "N/A",
    "fit": "FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "FITTED BLAZER WITH SHARARA",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "WITH BLACK OR GREY JUTTI\u2019S AND SILVER OR BLACK STATEMENT EARRINGS",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "GULZAAR PRINT BLAZER SET",
    "price": "N/A",
    "print": "GULZAAR",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "OVER SIZED BLAZER WITH FLARED PALAZZO PANTS",
    "category": "MATCHING MOODS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "LIBAAS PRINT CO-ORD",
    "price": "N/A",
    "print": "LIBAAS",
    "textile": "N/A",
    "fit": "SLIGHTLY RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "HALTER KURTI TOP WITH STRAIGHT BOTTOMS",
    "category": "MATCHING MOODS",
    "lining": "ONLY IN THE PANTS",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RANGREZ PRINT KAFTAN",
    "price": "10000",
    "print": "RANGREZ",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "1",
    "details": "KAFTAN WITH BORDER DETAILING BELT PATCH AND ON THE SLEEVE ENDINGS",
    "category": "FLOW STATE",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAAT PRINT KAFTAN",
    "price": "N/A",
    "print": "RAAT",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "1",
    "details": "PRINTED KATAAN WITH BORDER DETAILING BELT PATCH AND ON THE SLEEVE ENDINGS",
    "category": "FLOW STATE",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "LEHER PRINT OVER SIZED JACKET",
    "price": "6000",
    "print": "LEHER",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "MODAL SATIN",
    "components": "1",
    "details": "OVER SIZED JACKET, BUTTONS ONLY FOR SHOW",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL PRINT BLAZER DRESS",
    "price": "8200",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "BLAZER DRESS, WITH A PLUNGING NECKLINE, AND RUFFLES AT THE HEM",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "WHITE CROPPED BLAZER BLACK EMROIRDERY",
    "price": "7300/-",
    "print": "N/A",
    "textile": "N/A",
    "fit": "SLIGHTLY FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "BLACK SEQUINS HAND EMROIRDERY, PEPLUM OPEN BLAZER JACKET",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "BLACK LONG BLAZER",
    "price": "13000/-",
    "print": "N/A",
    "textile": "N/A",
    "fit": "FITTED",
    "fabric": "MUL",
    "components": "MUL",
    "details": "WHITE GOLD EMBROIDERED MOTIFS, LONG BLAZER",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "YEZ",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "15-20 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "62 BAGH PHULKARI JACKET",
    "price": "20000",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FITTED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "GOLD AND BROWN PHULKARI PARANTHA WORK",
    "category": "POWER LAYERS",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "60-75 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "WHITE GOLD PHULKARI BLAZER",
    "price": "8000",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FITTED",
    "fabric": "SUITING FABRIC",
    "components": "1",
    "details": "GOLDEN THREAD SPACED OUT PHULKARI WORK THROUGHOUT THE BLAZER",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "25-30 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL PRINT KAFTAN JACKET",
    "price": "4000",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "FLOWY PRINTED KAFTAN JACKET",
    "category": "POWER LAYERS",
    "lining": "NO",
    "pockets": "NO",
    "wash_care": "DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "WHITE GOLD SILVER KAFTAN JACKET",
    "price": "19000",
    "print": "N/A",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "HAND EMBROIDERED LOOSE FIT KAFTAN JACKET",
    "category": "POWER LAYERS",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "15-20 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "LIBAAS SAREE",
    "price": "15000",
    "print": "LIBAAS",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "NON PADDED HALTER COLLARED BLOUSE, SAREE WITH LACE WORK ON BORDERS",
    "category": "6 YARDS OF GOOD",
    "lining": "IN BLOUSE",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAVEL SAREE",
    "price": "15000",
    "print": "RAVEL",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "UNSTITCHED BLOUSE PIECE WITH SAREE THAT HAS LACE BORDER DETAILING",
    "category": "6 YARDS OF GOOD",
    "lining": "N/A",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE PRINT SAREE",
    "price": "15000",
    "print": "MARBLE",
    "textile": "N/A",
    "fit": "N/A",
    "fabric": "VISCOSE MUSLIN",
    "components": "2",
    "details": "BLOUSE: FULL SLEEVES PRINTED SLEEVES AND WHITE BODICE WITH BORDER DETAILING ON THE SAREE",
    "category": "6 YARDS OF GOOD",
    "lining": "IN BLOUSE",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "LEHER LENGHA SET",
    "price": "42000/-",
    "print": "LEHER",
    "textile": "N/A",
    "fit": "CUSTOMISED",
    "fabric": "MODAL SATIN",
    "components": "3",
    "details": "PEPLUM TOP WEAR WITH 34TH SLEEVES AND A FRONT SLIT, 18 KALI LENGHA AND A DUPATTA. ALL 3 COMPONENETS HAVE HAND EMBROIDERY",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "YES",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "30-35 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RAETAT PRINT COUPLE S",
    "price": "N/A",
    "print": "RAAT",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "MODAL SATIN AND VISCOSE MUSLIN",
    "components": "1+2",
    "details": "PRINTED NEHRU JACKET. SOLID BLACK SAREE WITH HAND EMBROIDRY ON PALLU AND PRINT BORDER DETAILING. UNSTITCHED BLOUSE",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "15-20 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RED WHITE EMBROIDERED LENGHA SET",
    "price": "48000",
    "print": "N/A",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "ARTIFICIAL SILK",
    "components": "2",
    "details": "FULL SLEEVES BLOUSE WITH EMBROIDERED CUFFS AND KALI LENNGHA WITH EMBROIDERY ON THE BELT AND LENGHA BOTTOM.",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "CAN BE ADDED",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "20-25 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE 2.0 PATIALA SUIT SET AND NEHRU JACKET",
    "price": "N/A",
    "print": "MARBLE 2.0",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "VISCOSE MUSLIN",
    "components": "3 + 1",
    "details": "BORDER DETAILING ON DUPATTA, SHORT KURTA WITH CHURIDAR SLEEVES AND PATIALA SALWAR. PRINTED NEHRU JACKET",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "GULBERG PRINT KURTA",
    "price": "7600/-",
    "print": "GULBERG",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "LINEN",
    "components": "1",
    "details": "PRINTED KURTA WITH AN APPLE CUT HEM",
    "category": "CUSTOM MADE",
    "lining": "NO",
    "pockets": "YES",
    "wash_care": "DRY CLEAN OR DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "SAGE GREEN AND IVORY BRIDAL LENGHA",
    "price": "2,49,000/-",
    "print": "N/A",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "LUXURY VEGAN SILK",
    "components": "4",
    "details": "HAND EMROIDERED. 2 DUPATTAS, BLOUSE AND 22 KALI LENGHA WITH CAN-CAN",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "3-4 MONTHS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "SAGE GREEN AND BEIGE GROOM\u2019S WEDDING OUTFIT",
    "price": "1,49,000/-",
    "print": "N/A",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "LUXURY VEGAN SILK",
    "components": "4",
    "details": "SAGE GREEN SHERWANI WITH BEIGE ANARKALI CHURI DAR AND BEIGE DUPATTA, ALL WITH HAND EMBROIDERY",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "2-3 MONTHS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE PRINT LENGHA BLAZER",
    "price": "15000",
    "print": "MARBLE",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "VISCOSE MUSLIN AND JUTE",
    "components": "2",
    "details": "CROPPED BLAZER WITH TWO TONED HIGH WAISTED LENGHA",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "CAN BE ADDED",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RANGREZ DHOTI KURTA SET",
    "price": "12000",
    "print": "RANGREZ",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "MODAL SATIN, GEORGETTE",
    "components": "3",
    "details": "PRINTED BLOUSE WITH DHOTI SKIRT AND GEORGETTE A LINE KURTI",
    "category": "CUSTOM MADE",
    "lining": "ONLY IN BLOUSE",
    "pockets": "NO",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "GULBER LEGHA CAPE SET",
    "price": "20,500/-",
    "print": "GULBERG",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "ARTIFICAL ORGANZA",
    "components": "3",
    "details": "CAPE WITH BORDER DETAIING, BLOUSE AND FLARED LENGHA WITH CAN CAN AND EMBROIDERED LACE BELT",
    "category": "CUSTOM MADE",
    "lining": "IN BLOUSE AND LENGHA",
    "pockets": "CAN BE ADDED",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE PRINT LENGHA SAREE FUSION",
    "price": "29000",
    "print": "MARBLE",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "VISCOSE MUSLIN",
    "components": "3",
    "details": "PRINTED SAREE WITH BORDER DETAILING, TWO TONED LENGHA AND PRINTED BLOUSE",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "CAN BE ADDED",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "RANGREZ PRINT SHORT DRESS",
    "price": "10000",
    "print": "RANGREZ",
    "textile": "N/A",
    "fit": "CUSTOM",
    "fabric": "MODAL SATIN",
    "components": "1",
    "details": "SHORT OFF SHOULDER DRESS, FITTED AT THE BUST, WITH A BIG BOW DETAILING AT THE BACK",
    "category": "CUSTOM MADE",
    "lining": "YES",
    "pockets": "CAN BE ADDED",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "DROP SHOULDER HEMP SHIRT",
    "price": "6500",
    "print": "N/A",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "HEMP",
    "components": "1",
    "details": "DROP SHOULDER BOXY SHIRT WITH BLAZER COLLAR",
    "category": "NATURAL LUXURY",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN OR DELICATE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "DROP SHOULDER EMBROIDERED SHIRT",
    "price": "5500",
    "print": "N/A",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "HAND EMBROIDERED PATCHES ON BOTH SLEEVES",
    "category": "NATURAL LUXURY",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "10-15 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "BLOCK PRINT DROP SHOULDER SHIRT",
    "price": "4500",
    "print": "N/A",
    "textile": "BLOCK PRINT",
    "fit": "RELAXED",
    "fabric": "MUL",
    "components": "1",
    "details": "BOXY OFF SHOULDER SHIRT WITH BLAZER COLLAR",
    "category": "PRINTED STORIES",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN OR DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MARBLE 2.0 DROP SHOULDER SHIRT",
    "price": "4700",
    "print": "MARBLE 2.0",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "PRINTED BOXY SHIRT WITH BLAZER COLLAR",
    "category": "PRINTED STORIES",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN OR DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "LIBAAS DROP SHOULDER SHIRT",
    "price": "4700/-",
    "print": "LIBAAS",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "BOXY DROP SHOULDER SHIRT WITH A NORMAL SHIRT COLLAR",
    "category": "PRINTED STORIES",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN OR DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "GULZAAR DROP SHOULDER SHIRT",
    "price": "4700/-",
    "print": "GULZAAR",
    "textile": "N/A",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "BOXY DROP SHOULDER SHIRT WITH A NORMAL SHIRT COLLAR",
    "category": "PRINTED STORIES",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN OR DELICATE MACHINE WASH",
    "styling_tip": "N/A",
    "delivery": "7-10 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "MULTI COLORED PHULKARI BUNDI JACKET",
    "price": "9700",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FITTED",
    "fabric": "COTTON MUL",
    "components": "1",
    "details": "CHOP FLOWER MULTI COLORED PHULKARI MOTIFS ON THIS NEHRU JACKET",
    "category": "MODERN CLASSICS",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "25-30 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "ALMOND WHITE AND BLUE PHULKARI BUNDI JACKET",
    "price": "6800/-",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "FIITED",
    "fabric": "JUTE COTTON",
    "components": "1",
    "details": "V NECK BUNDI JACKET WITH DARK AND PASTEL BLUE PHULKARI MOTIFS ALONG THE NECKLINE AND ON THE BACK",
    "category": "MODERN CLASSICS",
    "lining": "YES",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "20-25 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "WHITE AND GREEN OHULKARI SHIRT",
    "price": "11000/-",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "SLIGHTLY FITTED",
    "fabric": "SUITING FABRIC",
    "components": "1",
    "details": "DARK GREEN AND LIGHT GREEN PHULKARI WORK ON SLEEVES AND FRONT OF THE SHIRT ONLY",
    "category": "MODERN CLASSICS",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "25-30 DAYS",
    "img": "/assets/new_coll_3.png"
  },
  {
    "name": "WHITE PEACH RED FLORAL SHIRT",
    "price": "7700/-",
    "print": "N/A",
    "textile": "PHULKARI",
    "fit": "RELAXED",
    "fabric": "VISCOSE MUSLIN",
    "components": "1",
    "details": "PEACH AND RED PHULKARI ORK ON THE FOREAM AND BACK OF THE SHIRT",
    "category": "MODERN CLASSICS",
    "lining": "NO",
    "pockets": "N/A",
    "wash_care": "DRY CLEAN ONLY",
    "styling_tip": "N/A",
    "delivery": "20-25 DAYS",
    "img": "/assets/new_coll_3.png"
  }
];